### ISSUE TITLE
How to install for production use?

### ISSUE THREAD

**Issue by Ruriko** [pwp-app/pixiviz#14]
My OS is ubuntu 20.04 and webserver is nginx 1.18.0. Can you tell me how to install this for production use? here are the steps that I did:

```
apt-get install -y nodejs 
apt-get install git
git clone https://github.com/pwp-app/pixiviz
cd pixiviz
npm install
npm run build
```
nginx conf
```
server {
    server_name animeseries.xyz www.animeseries.xyz;

    access_log /var/log/nginx/animeseries.xyz.access.log ;
    error_log /var/log/nginx/animeseries.xyz.error.log;

    root /var/www/animeseries.xyz/htdocs/pixiviz/dist;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}
```

After installation I test my site but search results don't work. The results will always be empty so I check chrome console and saw that api is missing
![pix](https://user-images.githubusercontent.com/5670857/120060095-103e9c00-c099-11eb-9148-d76a04143705.png)

My live site is http://animeseries.xyz

**Comment by backrunner** [comment]
There's no problem to the front-end deployment, things you need to do is deploying this API server:
https://github.com/pwp-app/pixiviz-server
Then using nginx to proxy it to `/api`.

BTW, you also need to deploy your own image proxy server to fetch the images. My proxy servers will validate `Referer` in the requests, and they will not work properly in your site.
