### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Ruriko** [pwp-app/pixiviz#15]
Hi is it possible if you can make a dockerfile that will auto install frontend + backend + image proxy of your script?

**Comment by backrunner** [comment]
Sorry to tell you that I'm not gonna make a dockerfile right now, that's not in the development plan, and the next features will based on my self-made framework, there will be another server-side program, things will be more complicated if I integrate them into a one docker image. I will consider to pack frontend, backend and image proxy separately after completing the next features.
