### ISSUE TITLE
搭建相关问题与几个坑

### ISSUE THREAD

**Issue by lingcheng-1** [pwp-app/pixiviz#17]
我从Releases中下载了最新的代码版本
环境为Centos7、Nodejs14.17.0、npm6.14.13
按照README.md的要求执行npm install依赖按照后，出现报错。
npm WARN markdownlint-config-ali@0.1.1 requires a peer of markdownlint@^0.21.1 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
看到这里，后面几个小事情，前面的You must install peer dependencies yourself.这个问题很好解决。我尝试使用npm install npm -g对npm进行更新。然后删除node_modules文件夹，重新安装依赖。
然后出现了包的问题。
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npm.taobao.org/@nodelib/fs.stat/-/fs.stat-2.0.4.tgz - [not_found] document not found
npm ERR! 404 
npm ERR! 404  '@nodelib/fs.stat@https://registry.npm.taobao.org/@nodelib/fs.stat/-/fs.stat-2.0.4.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
嘛，我推断是npm源的问题。用nrm工具修改为npm官方源后再次重新安装依赖。不再报错。
然后我再进行README.md里面的下一步：运行本地服务器，实时编译 & 热重载
npm run serve
回显
 DONE  Compiled successfully in 23535ms  12:26:57 AM
  App running at:
  - Local:   https://localhost:8080/ 
  - Network: unavailable
  Note that the development build is not optimized.
  To create a production build, run npm run build.
由于是本地环境，我先用nginx反代一下。
顺利打开界面，但是使用不了功能。而且除首页外其他页面刷新后就502 Bad Gateway。
翻阅了一下代码发现用的是作者https://pixiviz.pwp.app站点的api。那么api问题排除。功能肯定是好的。应该在其他方面。
我决定暂时不管它了，先编译了再说。用npm run build进行编译。这时候就出现报错了。
[root@centos-s-1 pixiviz]# npm run build
> pixiviz@1.20.9 build
> node ./tools/processVersion.js && vue-cli-service build
Version info has been updated. v1.20.9
⠙  Building for production...
 WARNING  Compiled with 3 warnings    12:39:14 AM
 warning  
asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  img/landing.376fecb8.jpg (280 KiB)
  css/app.e9bc258c.css (276 KiB)
  js/chunk-vendors.abd175d1.js (251 KiB)
 warning  
entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.12 MiB)
      js/chunk-basic.eff48142.js
      css/chunk-element.df36f6eb.css
      js/chunk-element.a17d4b7a.js
      js/chunk-vendors.abd175d1.js
      css/app.e9bc258c.css
      js/app.17c4c3f1.js
 warning  
webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
  File                                                       Size                     Gzipped
  dist/js/chunk-vendors.abd175d1.js                          250.77 KiB               84.28 KiB
  dist/js/chunk-basic.eff48142.js                            232.62 KiB               75.10 KiB
  dist/js/chunk-element.a17d4b7a.js                          199.59 KiB               45.96 KiB
  dist/js/app.17c4c3f1.js                                    120.84 KiB               31.61 KiB
  dist/service-worker.js                                     2.42 KiB                 0.95 KiB
  dist/js/precache-manifest.5793c9f19e7239831479b9bcb106e    1.43 KiB                 0.55 KiB
  dcb.js
  dist/css/app.e9bc258c.css                                  275.98 KiB               41.86 KiB
  dist/css/chunk-element.df36f6eb.css                        65.58 KiB                11.05 KiB
  Images and other types of assets omitted.
 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
第一个报错是asset size limit。推断这些报错应该是webpack打包问题。删掉dist里面打包好的文件。也可以实验一下。是和在npm run serve这一步一样的结果使用上是有问题的。由于是webpack打包提示文件体积过大导致所以要在vue.config.js里面进行修改。
然而我改了好几次，问题还是没有解决。

**Comment by backrunner** [comment]
我这边用的是npm 7+官方源，如果对不上是有可能出问题的，这个我后续会标注在Readme里面。
对于包体积问题，这个是webpack抛出的warning，是正常的，我没有进一步切分包去达到不报错的打算。

**Comment by lingcheng-1** [comment]
![图片](https://user-images.githubusercontent.com/71746286/121465704-bdde7300-c9e8-11eb-82af-99c5cd5fec78.png)
嘛，打包问题是没有了。但是一直是这样。然后F5刷新一下页面就会404。
![图片](https://user-images.githubusercontent.com/71746286/121465823-e8303080-c9e8-11eb-8da5-dfac18970e85.png)
求教。嘛，我试了其他几个的pixivic等都有各种问题。就pixiviz比较适合。

**Comment by backrunner** [comment]
> ![图片](https://user-images.githubusercontent.com/71746286/121465704-bdde7300-c9e8-11eb-82af-99c5cd5fec78.png)
> 嘛，打包问题是没有了。但是一直是这样。然后F5刷新一下页面就会404。
> ![图片](https://user-images.githubusercontent.com/71746286/121465823-e8303080-c9e8-11eb-8da5-dfac18970e85.png)
> 求教。嘛，我试了其他几个的pixivic等都有各种问题。就pixiviz比较适合。

建议搜索部署vue站点的教程，你需要做rewrite到index.html

**Comment by lingcheng-1** [comment]
404问题我明白，需要重写地址。在nginx配置文件里面加入了
location / {
  try_files $uri $uri/ /index.html;
}
无法解决API问题。现在依旧是没有图片。

**Comment by backrunner** [comment]
> 404问题我明白，需要重写地址。在nginx配置文件里面加入了
> location / {
> try_files $uri $uri/ /index.html;
> }
> 无法解决API问题。现在依旧是没有图片。

API问题需要你自己解决，我在楼上提到了，你要自己部署pixiviz-server + 图片代理

**Comment by lingcheng-1** [comment]
ok，我试试

**Comment by backrunner** [comment]
因为数天这个issue没有更新，我这边暂时先关闭这个issue，如果还有其他问题可以另开issue或者重新打开这个issue。
