### ISSUE TITLE
How to change api link?

### ISSUE THREAD

**Issue by Ruriko** [pwp-app/pixiviz#18]
I want to change the api link cause my api is hosted on a subdomain and not a subdirectory. I tried editing vue.config.js to this 

```
devServer: {
    https: true,
    allowedHosts: ['animeseries.xyz'],
    proxy: {
      '/api': {
        target: 'https://api.animeseries.xyz',
        changeOrigin: true,
        pathRewrite: {
          '^/api': '',
        },
```

but the api link still goes to animeseries.xyz/api. I want it to go to api.animeseries.xyz. How do I change the api link?

**Comment by backrunner** [comment]
Modify the `config.json` in the `src` folder, there's a property called `api_prefix`.

**Comment by Ruriko** [comment]
the property `api_prefix` only adds a prefix after the base url which isn't what I want. I actually want to change the base url of the api

**Comment by backrunner** [comment]
> the property `api_prefix` only adds a prefix after the base url which isn't what I want. I actually want to change the base url of the api

> the property `api_prefix` only adds a prefix after the base url which isn't what I want. I actually want to change the base url of the api

If you have read the codes carefully, you can find out that the `api_prefix` can set the api urls to a subdomain as you requested.
Here's a piece of my code:
```js
this.axios
        .get(`${this.$config.api_prefix}/user/illusts`, {
          params: {
            id: this.id,
            page: this.page,
          },
        })
```
If you set the `api_prefix` to `https://api.animeseries.xyz`, the url will be `https://api.animeseries.xyz/user/illusts`.
