### ISSUE TITLE
How to remove browser extensions?

### ISSUE THREAD

**Issue by Ruriko** [pwp-app/pixiviz#19]
How do I remove all of the browser extensions like chrome?
![extension](https://user-images.githubusercontent.com/5670857/123372888-c37eb000-d5c7-11eb-9290-f0cfe2b6361b.jpg)

**Comment by backrunner** [comment]
That's the PWA support, not Chrome extension. See @vue/cli-plugin-pwa for more info.

**Comment by backrunner** [comment]
@Ruriko It seems like you build your own site with this project, could you take a look at the issue #20 to help us solve that issue?
