### ISSUE TITLE
[Bug] Statistics data pollution

### ISSUE THREAD

**Issue by backrunner** [pwp-app/pixiviz#20]
# Statistics data pollution issue

I have used Baidu statistics and FrontJS in the site to count the number of visits and collect program exceptions, the code related to these statistics was included in this project.

When you build this site using an older version of this project (below `1.23.1`) with your own domain, the stats code will also work on your site and pollute my site's stats.

If you build your own site with this project, we hope you can cooperate with us to solve the problem of statistics data pollution, we provide the following two options:

## First option: modify the existing code

The program requires you to operate to do the following two operations.
1, remove the Baidu statistics code in `public/index.html` (the `<script>` tag with `var _hmt` statement)
2、Remove `src/util/frontjs.js` and remove its reference and function calls in `main.js`

## Second option: upgrade the project

You need to upgrade your site to`v1.23.1` or newer, I've committed some changed to avoid statistics pollution issue.

Thanks for your understanding and cooperation.

**Comment by Ruriko** [comment]
I've updated and I was just wondering in config.json there is a properly called trust_host, do I leave that setting default or change it to my site address?

**Comment by backrunner** [comment]
> I've updated and I was just wondering in config.json there is a properly called trust_host, do I leave that setting default or change it to my site address?

Just leave it default. Thank you.

**Comment by backrunner** [comment]
> I've updated and I was just wondering in config.json there is a properly called trust_host, do I leave that setting default or change it to my site address?

Sorry to bother you, when I updated my test codes, I've noticed that there's a ridiculous bug in `src/main.js`, actually `main.js` will never call the `checkTrustHost` method, the judgement will always be `true`, so the pollution issue still exists.
In this case. we still need your cooperation, you need to upgrade the `main.js` to the latest. Thanks a lot.

**Comment by Ruriko** [comment]
Ok I've updated
