### ISSUE TITLE
[Suggestion] Dynamic Open Graph Meta Tags

### ISSUE THREAD

**Issue by Ruriko** [pwp-app/pixiviz#21]
Having dynamic og meta tags would be helpful since some may share links via social media like wechat, weibo, facebook

**Comment by backrunner** [comment]
WIP

**Comment by backrunner** [comment]
Related features has been updated to `master` branch, you can check it out now.

**Comment by Ruriko** [comment]
It seems like the meta tags for single image page doesn't work cause when social media bot visits the page it redirects them to the homepage so it gets the wrong meta tag info.
![ogtags](https://user-images.githubusercontent.com/5670857/126893936-5f0d746b-0457-47e1-b8be-927b5894e222.png)
You can try this debugger tool https://opengraphcheck.com/result.php?url=https%3A%2F%2Fpixiviz.pwp.app%2Fpic%2F91403647

**Comment by backrunner** [comment]
> It seems like the meta tags for single image page doesn't work cause when social media bot visits the page it redirects them to the homepage so it gets the wrong meta tag info.
> ![ogtags](https://user-images.githubusercontent.com/5670857/126893936-5f0d746b-0457-47e1-b8be-927b5894e222.png)
> You can try this debugger tool https://opengraphcheck.com/result.php?url=https%3A%2F%2Fpixiviz.pwp.app%2Fpic%2F91403647

You can try to share the page like a real user, the OG tags will be the right value.
This tool cannot execute JavaScript, in my solution, values will be modified when image loaded, or user enter to a new page.
