### ISSUE TITLE
[Suggestion] Add user profile links

### ISSUE THREAD

**Issue by Ruriko** [pwp-app/pixiviz#24]
Some pixiv users put links to their social media accounts and I was wondering if it's possible if you can include them on their user profile page?
![pixiv-profile](https://user-images.githubusercontent.com/5670857/129427810-2238202b-1b9c-4d5f-8500-80ad21ebcdfe.jpg)

**Comment by backrunner** [comment]
Through the API, I can only get the twitter link and artist's web homepage, I can show them in the profile page, but others can't.

**Comment by Ruriko** [comment]
Having only twitter & artist homepage is ok

**Comment by backrunner** [comment]
Related features has been merged into master branch.
