### ISSUE TITLE
How to change gif animation speed?

### ISSUE THREAD

**Issue by Ruriko** [pwp-app/pixiviz#25]
Where is the setting to change the GIF animation speed? cause it doesn't look like it's controlled by CSS

**Comment by backrunner** [comment]
See `play` method in this file: `src/util/ugoira.js`.

**Comment by Ruriko** [comment]
Can you tell me what do I change? I just want to slow down the animation speed like by making each frame 1second

**Comment by backrunner** [comment]
> Can you tell me what do I change? I just want to slow down the animation speed like by making each frame 1second

Speed is controlled by `delay`, it determines how long will the next frame be showed. Delay is in the frames data, you can write a method to modify the delay in each frame.
