### ISSUE TITLE
Certain images don't appear

### ISSUE THREAD

**Issue by Ruriko** [pwp-app/pixiviz#28]
There are specific images that don't appear using your script like this example: 
https://pixiviz.pwp.app/pic/92914666
https://www.pixiv.net/en/artworks/92914666

It appear that you need an pixiv account to view it. Is there a fix for this?

**Comment by backrunner** [comment]
Seems like a bug, I will figure out what happened later.

**Comment by backrunner** [comment]
I called `window.requestAnmiationFrame` at the wrong place, cause the bug, it has been fixed in `v1.24.7`.
