### ISSUE TITLE
数据无法加载，这个是API的问题吗

### ISSUE THREAD

**Issue by Twiyin0** [pwp-app/pixiviz#37]
作者大大好，
我今天在本地测试您的项目，出现下图问题
![image](https://user-images.githubusercontent.com/87588281/163563480-ce9cc621-4fec-4f5c-be27-e2e74a86a19c.png)
请问，这个项目是需要其他API支持吗？
我的node版本是v16.14.2, npm版本8.7.0

**Comment by backrunner** [comment]
看上去日志里有两个问题：
1、shareToken报错，我在项目里追求一些新特性放弃了一些兼容性，请使用最新版本Chrome来debug
2、API等网络错误，为了防止服务滥用项目的服务器都对域名有严格要求，请使用whistle代理等方法将pixiviz.pwp.app代理到本地

**Comment by Twiyin0** [comment]
使用chrome也无法解决shareToken的报错，
![image](https://user-images.githubusercontent.com/87588281/163578235-4c3ccf42-bb8e-45c7-a044-3251dfb51006.png)
如果想自己搭建API的话可以直接使用[pixiviz-server](https://github.com/pwp-app/pixiviz-server)吗？

**Comment by backrunner** [comment]
> 使用chrome也无法解决shareToken的报错， ![image](https://user-images.githubusercontent.com/87588281/163578235-4c3ccf42-bb8e-45c7-a044-3251dfb51006.png) 如果想自己搭建API的话可以直接使用[pixiviz-server](https://github.com/pwp-app/pixiviz-server)吗？

shareToken的问题，review了一下代码存在一个bug，稍后会修复。还是建议把pixiviz.pwp.app代理到本地调试，使用localhost是不推荐的。
自建API使用pixiviz-server是可以的，但你需要自己准备环境和帐号token，具体可以参考https://github.com/pwp-app/pixiviz-server/issues/1

**Comment by Twiyin0** [comment]
好的，谢谢大大

**Comment by Twiyin0** [comment]
作者大大好，
我这两天试了下使用`whistle`代理，但还是无法解决`https://pixiviz-api-hk.pwp.link/`的跨域问题。
![image](https://user-images.githubusercontent.com/87588281/163708895-923680cb-64fa-489b-a0ce-6419782d9f30.png)
因为对whistle代理还是特别懵的状态，可以请教一下是怎么配置的吗？
![image](https://user-images.githubusercontent.com/87588281/163708923-6d9cea05-c132-48f9-8b81-50b1186e5981.png)
![image](https://user-images.githubusercontent.com/87588281/163708933-89cb7e43-933c-4b01-a9ae-25ad93da33bb.png)

**Comment by backrunner** [comment]
whistle的配置写反了，前后调换一下，用pixiviz.pwp.app访问

**Comment by Twiyin0** [comment]
那如果放在服务端，可以使用自己的域名访问吗？

**Comment by backrunner** [comment]
如果你要自己部署一份Pixiviz，图片代理和API都需要使用你自己的。

也就是说你要部署一整套服务，并且将这个项目config.json里的服务地址指向你自己的API和图片代理才能正常使用。

原站所有后端接口都是私有的，毕竟这个涉及到运营成本，还请理解。

**Comment by backrunner** [comment]
这个issue我先close了，如果有任何其他问题欢迎开新的issue询问。
