### ISSUE TITLE
网站访问不了

### ISSUE THREAD

**Issue by XJYU666** [pwp-app/pixiviz#40]
网站访问不了
![摄像 2022_7_19 10_23_43](https://user-images.githubusercontent.com/104675974/179650574-275b5cb2-61f9-4d45-97f3-269189d3d3d4.png)
![pwp space 和另外 8 个页面 - 个人 - Microsoft​ Edge 2022_7_19 10_17_59 (1)](https://user-images.githubusercontent.com/104675974/179650597-28f5fcfa-e71a-4be3-8bf4-b0fcd1e15edf.png)

**Comment by backrunner** [comment]
请前往爱发电，你想要的东西在那
