### ISSUE TITLE
是否考虑提供Android客户端

### ISSUE THREAD

**Issue by amokiel** [pwp-app/pixiviz#42]
网页版很好用，体验也不错，要是有个Android客户端就再好不过了。简单打包能用就行。辛苦了，非常感谢，希望可以考虑一下，拜托了！

**Comment by backrunner** [comment]
> 网页版很好用，体验也不错，要是有个Android客户端就再好不过了。简单打包能用就行。辛苦了，非常感谢，希望可以考虑一下，拜托了！

目前暂时没有支持客户端的打算，站点本身支持PWA，可以添加到桌面后以全屏模式使用。
（不同品牌的手机/浏览器支持情况不同，可以先尝试一下）
