### ISSUE TITLE
建议：请问有没有下载图片自定义名字的功能

### ISSUE THREAD

**Issue by cloudswzy** [pwp-app/pixiviz#7]
![image](https://user-images.githubusercontent.com/23417762/98461685-3bd76300-21e9-11eb-9fe0-b52818028b83.png)
类似于pixiv toolkit的下载功能，目前我只能通过图片另存为的方式下载，并且图片的名称是一串无意义的编码

**Comment by backrunner** [comment]
我考虑一下是否要给所有详情页在右侧都加一个下载，然后把你提到的功能做进去，感谢反馈~

**Comment by cloudswzy** [comment]
嗯~ o(*￣▽￣*)o，感谢dalao回复。另外我在使用的时候，操作大概是点进作者首页，点进插图详情，图片另存为。从插图详情退出到作者首页的时候，页面重加载了，并没有定位到我之前的浏览位置，如果该作者图片较多的话，重新加载的时间会相对较长。希望能有个在缩略图提供下载的地方，减少载图的频率。

**Comment by backrunner** [comment]
> 嗯~ o(_￣▽￣_)o，感谢dalao回复。另外我在使用的时候，操作大概是点进作者首页，点进插图详情，图片另存为。从插图详情退出到作者首页的时候，页面重加载了，并没有定位到我之前的浏览位置，如果该作者图片较多的话，重新加载的时间会相对较长。希望能有个在缩略图提供下载的地方，减少载图的频率。

缩略图的右键菜单一直有做但是也还没搞，开发上需要不少时间，目前我个人最近一段时间比较紧，所以要上新功能得要一些时间吧pwp。
作者页会重加载这个问题我找个时间优先优化掉。

**Comment by cloudswzy** [comment]
dalao牛逼，辛苦了。

**Comment by backrunner** [comment]
进度update：功能在做了，新版本还做了一些其他的东西，下载这一块这周内跟新版本一起上

**Comment by backrunner** [comment]
新版本已push，close
